#                                     #
#            CHAT SECTION             #
#                                     #
#
chat:
  cooldown:
    enabled: true
    duration: 5s
    group-duration:
      vip: 2s
