name: tChat
version: ${project.version}
main: me.hardstyl3r.tchat.TChat
api-version: 1.20
authors: [ hardStyl3r ]
description: Toolsies addon to manage the chat
depend: [ toolsies ]
softdepend: [ tPerms ]
commands:
  chat:
  tchat:
  msg:
    aliases: [message, pm, m, tell, whisper]
  reply:
    aliases: [r]
  msgtoggle:
    aliases: [mtoggle, rtoggle, messagetoggle, pmtoggle, telltoggle, whispertoggle]
  socialspy:

