name: tBans
version: ${project.version}
main: me.hardstyl3r.tbans.TBans
api-version: 1.18
authors: [ hardStyl3r ]
description: Toolsies addon to support punishments
depend: [ toolsies ]
commands:
  ban:
  banlist:
  unban:
  tempban:
  getban:
  ban-ip:
  unban-ip:
  warn:
  unwarn:
  warns:
  getwarn:
  mute:
  tempmute:
  tempwarn:
  unmute:
  kick:
  tempban-ip:
  getban-ip: