# toolsies-0.5-BETA config
#                                            #
#              DATABASE SECTION              #
#                                            #
# https://github.com/brettwooldridge/HikariCP
#
# warn: you need to create database `toolsies`
database:
  host: 127.0.0.1
  port: 3306
  user:
  password:

#                                            #
#              DEFAULT SECTION               #
#                                            #
#
# this is unified section for the default values.
default:
  locale: 'pl'

#                                            #
#               LOCALE SECTION               #
#                                            #
#
# `locales` accepts the ID of locales, which is
# the value after the dash in .jar root
#
# non-existent languages will not cause a crash
# but empty list will.
locales:
  - 'pl'
  - 'en'