name: toolsies
version: ${project.version}
main: me.hardstyl3r.toolsies.Toolsies
api-version: 1.20
authors: [ hardStyl3r ]
description: nifty gifties
commands:
  toolsies:
  kit:
  locale:
  broadcast:
  broadcastraw:
  getspawn:
  setspawn:
  spawn:
  more:
