name: tAuth
version: ${project.version}
main: me.hardstyl3r.tauth.TAuth
api-version: 1.19
authors: [ hardStyl3r ]
description: Toolsies addon to support authentication
depend: [ toolsies, tPerms ]

commands:
  login:
  register:
  logout:
  auth:
  changepassword:
  playtime:
  email:
