name: tPerms
version: ${project.version}
main: me.hardstyl3r.tperms.TPerms
api-version: 1.17
authors: [ hardStyl3r ]
description: Toolsies addon to support permissions
depend: [ toolsies ]
commands:
  group:
  permission: